#ifndef COMMANDSYMBOL_HPP
#define COMMANDSYMBOL_HPP

enum class CommandSymbolBit : int {
    NonTerminalBit   = 0x100000,
    EnumBit          = 0x200000,
    OptionalBit      = 0x400000,
    FactorizationBit = 0x800000,
    PostfixBit       = 0x1000000,
    EnumValueBit     = 0x2000000,
    SoftEnumBit      = 0x4000000
};

constexpr int operator|(const int lhs, CommandSymbolBit rhs) {
    return lhs | static_cast<int>(rhs);
};

enum class CommandSymbol : int {
    Epsilon                   = CommandSymbolBit::NonTerminalBit,
    Int                       = 0x01 | CommandSymbolBit::NonTerminalBit,
    Float                     = 0x02 | CommandSymbolBit::NonTerminalBit,
    Val                       = 0x03 | CommandSymbolBit::NonTerminalBit,
    RVal                      = 0x04 | CommandSymbolBit::NonTerminalBit,
    WildcardInt               = 0x05 | CommandSymbolBit::NonTerminalBit,
    Operator                  = 0x06 | CommandSymbolBit::NonTerminalBit,
    CompareOperator           = 0x07 | CommandSymbolBit::NonTerminalBit,
    Selection                 = 0x08 | CommandSymbolBit::NonTerminalBit,
    StandaloneSelection       = 0x09 | CommandSymbolBit::NonTerminalBit,
    WildcardSelection         = 0x0a | CommandSymbolBit::NonTerminalBit,
    NonIdSelector             = 0x0b | CommandSymbolBit::NonTerminalBit,
    ScoresArg                 = 0x0c | CommandSymbolBit::NonTerminalBit,
    ScoresArgs                = 0x0d | CommandSymbolBit::NonTerminalBit,
    ScoreSelectParam          = 0x0e | CommandSymbolBit::NonTerminalBit,
    ScoreSelector             = 0x0f | CommandSymbolBit::NonTerminalBit,
    TagSelector               = 0x10 | CommandSymbolBit::NonTerminalBit,
    FilePath                  = 0x11 | CommandSymbolBit::NonTerminalBit,
    FilePathVal               = 0x12 | CommandSymbolBit::NonTerminalBit,
    FilePathCont              = 0x13 | CommandSymbolBit::NonTerminalBit,
    IntegerRangeVal           = 0x14 | CommandSymbolBit::NonTerminalBit,
    IntegerRangePostVal       = 0x15 | CommandSymbolBit::NonTerminalBit,
    IntegerRange              = 0x16 | CommandSymbolBit::NonTerminalBit,
    FullIntegerRange          = 0x17 | CommandSymbolBit::NonTerminalBit,
    RationalRangeVal          = 0x18 | CommandSymbolBit::NonTerminalBit,
    RationalRangePostVal      = 0x19 | CommandSymbolBit::NonTerminalBit,
    RationalRange             = 0x1a | CommandSymbolBit::NonTerminalBit,
    FullRationalRange         = 0x1b | CommandSymbolBit::NonTerminalBit,
    SelArgs                   = 0x1c | CommandSymbolBit::NonTerminalBit,
    Args                      = 0x1d | CommandSymbolBit::NonTerminalBit,
    Arg                       = 0x1e | CommandSymbolBit::NonTerminalBit,
    MArg                      = 0x1f | CommandSymbolBit::NonTerminalBit,
    MValue                    = 0x20 | CommandSymbolBit::NonTerminalBit,
    NameArg                   = 0x21 | CommandSymbolBit::NonTerminalBit,
    TypeArg                   = 0x22 | CommandSymbolBit::NonTerminalBit,
    FamilyArg                 = 0x23 | CommandSymbolBit::NonTerminalBit,
    HasPermissionArg          = 0x24 | CommandSymbolBit::NonTerminalBit,
    HasPermissionArgs         = 0x25 | CommandSymbolBit::NonTerminalBit,
    HasPermissionSelector     = 0x26 | CommandSymbolBit::NonTerminalBit,
    HasPermissionElement      = 0x27 | CommandSymbolBit::NonTerminalBit,
    HasPermissionElements     = 0x28 | CommandSymbolBit::NonTerminalBit,
    TagArg                    = 0x29 | CommandSymbolBit::NonTerminalBit,
    HasItemElement            = 0x2a | CommandSymbolBit::NonTerminalBit,
    HasItemElements           = 0x2b | CommandSymbolBit::NonTerminalBit,
    HasItemArg                = 0x2c | CommandSymbolBit::NonTerminalBit,
    HasItemArgs               = 0x2d | CommandSymbolBit::NonTerminalBit,
    HasItemSelector           = 0x2e | CommandSymbolBit::NonTerminalBit,
    EquipmentSlotEnum         = 0x2f | CommandSymbolBit::NonTerminalBit,
    PropertyValue             = 0x30 | CommandSymbolBit::NonTerminalBit,
    HasPropertyParamValue     = 0x31 | CommandSymbolBit::NonTerminalBit,
    HasPropertyParamEnumValue = 0x32 | CommandSymbolBit::NonTerminalBit,
    HasPropertyArg            = 0x33 | CommandSymbolBit::NonTerminalBit,
    HasPropertyArgs           = 0x34 | CommandSymbolBit::NonTerminalBit,
    HasPropertyElement        = 0x35 | CommandSymbolBit::NonTerminalBit,
    HasPropertyElements       = 0x36 | CommandSymbolBit::NonTerminalBit,
    HasPropertySelector       = 0x37 | CommandSymbolBit::NonTerminalBit,
    Id                        = 0x38 | CommandSymbolBit::NonTerminalBit,
    IdCont                    = 0x39 | CommandSymbolBit::NonTerminalBit,
    CoordXInt                 = 0x3a | CommandSymbolBit::NonTerminalBit,
    CoordYInt                 = 0x3b | CommandSymbolBit::NonTerminalBit,
    CoordZInt                 = 0x3c | CommandSymbolBit::NonTerminalBit,
    CoordXFloat               = 0x3d | CommandSymbolBit::NonTerminalBit,
    CoordYFloat               = 0x3e | CommandSymbolBit::NonTerminalBit,
    CoordZFloat               = 0x3f | CommandSymbolBit::NonTerminalBit,
    Position                  = 0x40 | CommandSymbolBit::NonTerminalBit,
    PositionFloat             = 0x41 | CommandSymbolBit::NonTerminalBit,
    MessageExp                = 0x42 | CommandSymbolBit::NonTerminalBit,
    Message                   = 0x43 | CommandSymbolBit::NonTerminalBit,
    MessageRoot               = 0x44 | CommandSymbolBit::NonTerminalBit,
    PostSelector              = 0x45 | CommandSymbolBit::NonTerminalBit,
    RawText                   = 0x46 | CommandSymbolBit::NonTerminalBit,
    RawTextCont               = 0x47 | CommandSymbolBit::NonTerminalBit,
    JsonValue                 = 0x48 | CommandSymbolBit::NonTerminalBit,
    JsonField                 = 0x49 | CommandSymbolBit::NonTerminalBit,
    JsonObject                = 0x4a | CommandSymbolBit::NonTerminalBit,
    JsonObjectFields          = 0x4b | CommandSymbolBit::NonTerminalBit,
    JsonObjectCont            = 0x4c | CommandSymbolBit::NonTerminalBit,
    JsonArray                 = 0x4d | CommandSymbolBit::NonTerminalBit,
    JsonArrayValues           = 0x4e | CommandSymbolBit::NonTerminalBit,
    JsonArrayCont             = 0x4f | CommandSymbolBit::NonTerminalBit,
    BlockState                = 0x50 | CommandSymbolBit::NonTerminalBit,
    BlockStateKey             = 0x51 | CommandSymbolBit::NonTerminalBit,
    BlockStateValue           = 0x52 | CommandSymbolBit::NonTerminalBit,
    BlockStateValues          = 0x53 | CommandSymbolBit::NonTerminalBit,
    BlockStateArray           = 0x54 | CommandSymbolBit::NonTerminalBit,
    BlockStateArrayCont       = 0x55 | CommandSymbolBit::NonTerminalBit,
    Command                   = 0x56 | CommandSymbolBit::NonTerminalBit,
    SlashCommand              = 0x57 | CommandSymbolBit::NonTerminalBit,
    CodeBuilderArg            = 0x58 | CommandSymbolBit::NonTerminalBit,
    CodeBuilderArgs           = 0x59 | CommandSymbolBit::NonTerminalBit,
    CodeBuilderSelectParam    = 0x5a | CommandSymbolBit::NonTerminalBit,
    CodeBuilderSelector       = 0x5b | CommandSymbolBit::NonTerminalBit
};

#endif // !COMMANDSYMBOL_HPP