#include "GameRules.hpp"

#include <memory>

void GameRules::initialize() {
    this->mGameRules.emplace_back(GameRules::CommandBlockOutput);
    this->mGameRules.emplace_back(GameRules::DoDaylightCycle);
    this->mGameRules.emplace_back(GameRules::DoEntityDrops);
    this->mGameRules.emplace_back(GameRules::DoFireTick);
    this->mGameRules.emplace_back(GameRules::RecipesUnlock);
    this->mGameRules.emplace_back(GameRules::DoLimitedCrafting);
    this->mGameRules.emplace_back(GameRules::DoMobLoot);
    this->mGameRules.emplace_back(GameRules::DoMobSpawning);
    this->mGameRules.emplace_back(GameRules::DoTileDrops);
    this->mGameRules.emplace_back(GameRules::DoWeatherCycle);
    this->mGameRules.emplace_back(GameRules::DrowningDamage);
    this->mGameRules.emplace_back(GameRules::FallDamage);
    this->mGameRules.emplace_back(GameRules::FireDamage);
    this->mGameRules.emplace_back(GameRules::KeepInventory);
    this->mGameRules.emplace_back(GameRules::MobGriefing);
    this->mGameRules.emplace_back(GameRules::Pvp);
    this->mGameRules.emplace_back(GameRules::ShowCoordinates);
    this->mGameRules.emplace_back(GameRules::ShowDaysPlayed);
    this->mGameRules.emplace_back(GameRules::DoNaturalRegeneration);
    this->mGameRules.emplace_back(GameRules::DoTntExplode);
    this->mGameRules.emplace_back(GameRules::SendCommandFeedback);
    this->mGameRules.emplace_back(GameRules::LocatorBar);
    this->mGameRules.emplace_back(GameRules::MaxCommandChainLength);
    this->mGameRules.emplace_back(GameRules::DoInsomnia);
    this->mGameRules.emplace_back(GameRules::CommandBlocksEnabled);
    this->mGameRules.emplace_back(GameRules::RandomTickSpeed);
    this->mGameRules.emplace_back(GameRules::DoImmediateRespawn);
    this->mGameRules.emplace_back(GameRules::ShowDeathMessages);
    this->mGameRules.emplace_back(GameRules::FunctionCommandLimit);
    this->mGameRules.emplace_back(GameRules::PlayerSpawnRadius);
    this->mGameRules.emplace_back(GameRules::ShowTags);
    this->mGameRules.emplace_back(GameRules::FreezeDamage);
    this->mGameRules.emplace_back(GameRules::RespawnBlocksExplode);
    this->mGameRules.emplace_back(GameRules::ShowBorderEffect);
    this->mGameRules.emplace_back(GameRules::ShowRecipeMessages);
    this->mGameRules.emplace_back(GameRules::PlayerSleepingPercentage);
    this->mGameRules.emplace_back(GameRules::ProjectilesCanBreakBlocks);
    this->mGameRules.emplace_back(GameRules::TntExplosionDropDecay);
};

GameRule GameRules::CommandBlockOutput = GameRule{ "commandblockoutput" }.setValue(true);
GameRule GameRules::DoDaylightCycle = GameRule{ "dodaylightcycle" }.setValue(true);
GameRule GameRules::DoEntityDrops = GameRule{ "doentitydrops" }.setValue(true);
GameRule GameRules::DoFireTick = GameRule{ "dofiretick" }.setValue(true);
GameRule GameRules::RecipesUnlock = GameRule{ "recipesunlock" }.setValue(true);
GameRule GameRules::DoLimitedCrafting = GameRule{ "dolimitedcrafting" }.setValue(false);
GameRule GameRules::DoMobLoot = GameRule{ "domobloot" }.setValue(true);
GameRule GameRules::DoMobSpawning = GameRule{ "domobspawning" }.setValue(true);
GameRule GameRules::DoTileDrops = GameRule{ "dotiledrops" }.setValue(true);
GameRule GameRules::DoWeatherCycle = GameRule{ "doweathercycle" }.setValue(true);
GameRule GameRules::DrowningDamage = GameRule{ "drowningdamage" }.setValue(true);
GameRule GameRules::FallDamage = GameRule{ "falldamage" }.setValue(true);
GameRule GameRules::FireDamage = GameRule{ "firedamage" }.setValue(true);
GameRule GameRules::KeepInventory = GameRule{ "keepinventory" }.setValue(false);
GameRule GameRules::MobGriefing = GameRule{ "mobgriefing" }.setValue(true);
GameRule GameRules::Pvp = GameRule{ "pvp" }.setValue(true);
GameRule GameRules::ShowCoordinates = GameRule{ "showcoordinates" }.setValue(true);
GameRule GameRules::ShowDaysPlayed = GameRule{ "showdaysplayed" }.setValue(true);
GameRule GameRules::DoNaturalRegeneration = GameRule{ "donaturalregeneration" }.setValue(true);
GameRule GameRules::DoTntExplode = GameRule{ "dotntexplode" }.setValue(true);
GameRule GameRules::SendCommandFeedback = GameRule{ "sendcommandfeedback" }.setValue(true);
GameRule GameRules::LocatorBar = GameRule{ "locatorbar" }.setValue(true);
GameRule GameRules::MaxCommandChainLength = GameRule{ "maxcommandchainlength" }.setValue(65535);
GameRule GameRules::DoInsomnia = GameRule{ "doinsomnia" }.setValue(true);
GameRule GameRules::CommandBlocksEnabled = GameRule{ "commandblocksenabled" }.setValue(false);
GameRule GameRules::RandomTickSpeed = GameRule{ "randomtickspeed" }.setValue(1);
GameRule GameRules::DoImmediateRespawn = GameRule{ "doimmediaterespawn" }.setValue(false);
GameRule GameRules::ShowDeathMessages = GameRule{ "showdeathmessages" }.setValue(true);
GameRule GameRules::FunctionCommandLimit = GameRule{ "functioncommandlimit" }.setValue(10000);
GameRule GameRules::PlayerSpawnRadius = GameRule{ "spawnradius" }.setValue(10);
GameRule GameRules::ShowTags = GameRule{ "showtags" }.setValue(true);
GameRule GameRules::FreezeDamage = GameRule{ "freezedamage" }.setValue(true);
GameRule GameRules::RespawnBlocksExplode = GameRule{ "respawnblocksexplode" }.setValue(true);
GameRule GameRules::ShowBorderEffect = GameRule{ "showbordereffect" }.setValue(true);
GameRule GameRules::ShowRecipeMessages = GameRule{ "showrecipemessages" }.setValue(true);
GameRule GameRules::PlayerSleepingPercentage = GameRule{ "playersleepingpercentage" }.setValue(100);
GameRule GameRules::ProjectilesCanBreakBlocks = GameRule{ "projectilescanbreakblocks" }.setValue(true);
GameRule GameRules::TntExplosionDropDecay = GameRule{ "tntexplosiondropdecay" }.setValue(false);