#pragma once
#include "../Packet.hpp"

enum class DisconnectReason
{
    Unknown = 0,
    CantConnectNoInternet = 1,
    NoPermissions = 2,
    UnrecoverableError = 3,
    ThirdPartyBlocked = 4,
    ThirdPartyNoInternet = 5,
    ThirdPartyBadIP = 6,
    ThirdPartyNoServerOrServerLocked = 7,
    VersionMismatch = 8,
    SkinIssue = 9,
    InviteSessionNotFound = 10,
    EduLevelSettingsMissing = 11,
    LocalServerNotFound = 12,
    LegacyDisconnect = 13,
    UserLeaveGameAttempted = 14,
    PlatformLockedSkinsError = 15,
    RealmsWorldUnassigned = 16,
    RealmsServerCantConnect = 17,
    RealmsServerHidden = 18,
    RealmsServerDisabledBeta = 19,
    RealmsServerDisabled = 20,
    CrossPlatformDisabled = 21,
    CantConnect = 22,
    SessionNotFound = 23,
    ClientSettingsIncompatibleWithServer = 24,
    ServerFull = 25,
    InvalidPlatformSkin = 26,
    EditionVersionMismatch = 27,
    EditionMismatch = 28,
    LevelNewerThanExeVersion = 29,
    NoFailOccurred = 30,
    BannedSkin = 31,
    Timeout = 32,
    ServerNotFound = 33,
    OutdatedServer = 34,
    OutdatedClient = 35,
    NoPremiumPlatform = 36,
    MultiplayerDisabled = 37,
    NoWiFi = 38,
    WorldCorruption = 39,
    NoReason = 40,
    Disconnected,
    InvalidPlayer,
    LoggedInOtherLocation,
    ServerIdConflict,
    NotAllowed,
    NotAuthenticated,
    InvalidTenant,
    UnknownPacket,
    UnexpectedPacket,
    InvalidCommandRequestPacket,
    HostSuspended,
    LoginPacketNoRequest,
    LoginPacketNoCert,
    MissingClient,
    Kicked,
    KickedForExploit,
    KickedForIdle,
    ResourcePackProblem,
    IncompatiblePack,
    OutOfStorage,
    InvalidLevel,
    DisconnectPacket_DEPRECATED,
    BlockMismatch,
    InvalidHeights,
    InvalidWidths,
    ConnectionLost,
    ZombieConnection,
    Shutdown,
    ReasonNotSet_DEPRECATED,
    LoadingStateTimeout,
    ResourcePackLoadingFailed,
    SearchingForSessionLoadingScreenFailed,
    NetherNetProtocolVersion,
    SubsystemStatusError,
    EmptyAuthFromDiscovery,
    EmptyUrlFromDiscovery,
    ExpiredAuthFromDiscovery,
    UnknownSignalServiceSignInFailure,
    XBLJoinLobbyFailure,
    UnspecifiedClientInstanceDisconnection,
    NetherNetSessionNotFound,
    NetherNetCreatePeerConnection,
    NetherNetICE,
    NetherNetConnectRequest,
    NetherNetConnectResponse,
    NetherNetNegotiationTimeout,
    NetherNetInactivityTimeout,
    StaleConnectionBeingReplaced,
    RealmsSessionNotFound_DEPRECATED,
    BadPacket,
    NetherNetFailedToCreateOffer,
    NetherNetFailedToCreateAnswer,
    NetherNetFailedToSetLocalDescription,
    NetherNetFailedToSetRemoteDescription,
    NetherNetNegotiationTimeoutWaitingForResponse,
    NetherNetNegotiationTimeoutWaitingForAccept,
    NetherNetIncomingConnectionIgnored,
    NetherNetSignalingParsingFailure,
    NetherNetSignalingUnknownError,
    NetherNetSignalingUnicastDeliveryFailed,
    NetherNetSignalingBroadcastDeliveryFailed,
    NetherNetSignalingGenericDeliveryFailed,
    EditorMismatchEditorWorld,
    EditorMismatchVanillaWorld,
    WorldTransferNotPrimaryClient,
    RequestServerShutdown,
    ClientGameSetupCancelled,
    ClientGameSetupFailed,
    NoVenue,
    NetherNetSignalingSigninFailed,
    SessionAccessDenied,
    ServiceSigninIssue,
    NetherNetNoSignalingChannel,
    NetherNetNotLoggedIn,
    NetherNetClientSignalingError
};

class DisconnectPacket : public Packet
{
public:
    DisconnectReason reason;
    bool skipMessage;
    std::string message;

public:
    DisconnectPacket()
        : Packet("DisconnectPacket", MinecraftPacketIds::Disconnect) {};

    void read(BinaryStream& stream) override;
    void write(BinaryStream& stream) override;
};